# Generated by Django 5.1.5 on 2025-02-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('post_season', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('player_number', models.IntegerField()),
                ('player_height', models.CharField(max_length=225)),
                ('player_weight', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('position', models.CharField(max_length=225)),
                ('year_started', models.IntegerField()),
                ('draft_year', models.IntegerField()),
                ('draft_pick', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=225)),
                ('team_city', models.CharField(max_length=225)),
                ('team_conference', models.CharField(max_length=225)),
                ('team_division', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minutes', models.IntegerField()),
                ('points', models.IntegerField()),
                ('offensive_rebounds', models.IntegerField()),
                ('defensive_rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('tpm', models.IntegerField()),
                ('tpa', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='api.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='api.team'),
        ),
    ]
